version: '3'

services:
    mysql:
        image: mysql:latest
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./data:/var/lib/mysql/
        ports:
            - ${MYSQL_PORT}:3306
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
        networks:
            - symfony
            - mysql
    # beekeeper:
    #     depends_on:
    #         - mysql
    #     build:
    #         context: .
    #         dockerfile: docker/beekeeper/Dockerfile
    #     ports:
    #         - 127.0.0.1:9999:8080
    #     environment:
    #         net: host
    #         DISPLAY: ${DISPLAY}
    #     volumes:
    #         - $home/.Xauthority:/root/.Xauthority
    #         - /tmp/.X11-unix:/tmp/.X11-unix
    php:
        depends_on:
            - mysql
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${PHP_TIMEZONE}
        restart: unless-stopped
        healthcheck:
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 30s
        volumes:
            - ./www/:/var/www/symfony/
        networks:
            - symfony
            - mysql
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:${MYSQL_PORT}/${MYSQL_DATABASE}
            - PHP_TIMEZONE=${PHP_TIMEZONE}
    nginx:
        depends_on:
            - php
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        restart: unless-stopped
        volumes:
            - ./www/:/var/www/symfony/
        ports:
            - 80:80
            - 443:443
        networks:
            - symfony
            - mysql
        volumes:
            - ./data/nginx:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        #command:
        #- "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
    db_app:

networks:
    symfony:
    mysql:
