version: '3'

services:
    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
          - ./data:/var/lib/mysql/
        ports:
            - ${MYSQL_PORT}:3306
    # beekeeper:
    #     depends_on:
    #         - mysql
    #     build:
    #         context: .
    #         dockerfile: docker/beekeeper/Dockerfile
    #     ports:
    #         - 127.0.0.1:9999:8080
    #     environment:
    #         net: host
    #         DISPLAY: ${DISPLAY}
    #     volumes:
    #         - $home/.Xauthority:/root/.Xauthority
    #         - /tmp/.X11-unix:/tmp/.X11-unix
    php:
        depends_on:
            - mysql
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${PHP_TIMEZONE}
        volumes:
            - ./www/:/var/www/symfony/
        networks:
            - symfony
        environment:
          - APP_ENV=${APP_ENV}
          - APP_SECRET=${APP_SECRET}
          - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@127.0.0.1:${MYSQL_PORT}/${MYSQL_DATABASE}
          - PHP_TIMEZONE=${PHP_TIMEZONE}
    nginx:
        depends_on:
            - php
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./www/:/var/www/symfony/
        ports:
            - 80:80
            - 443:443
        networks:
            - symfony
volumes:
    db_app:

networks:
    symfony:
