version: '3'

services:
    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: kosmood
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
          - ./data:/var/lib/mysql/
        ports:
            - 3306:3306
    adminer:
      image: adminer
      restart: always
      ports:
        - 8182:8080
    php:
        depends_on:
            - mysql
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${PHP_TIMEZONE}
        volumes:
            - ./www/:/var/www/symfony/
        networks:
            - symfony
        environment:
          - APP_ENV=${APP_ENV}
          - APP_SECRET=${APP_SECRET}
          - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@127.0.0.1:3306/${MYSQL_DATABASE}
          - PHP_TIMEZONE=${PHP_TIMEZONE}
    nginx:
        depends_on:
            - php
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./www/:/var/www/symfony/
        ports:
            - 80:80
            - 443:443
        networks:
            - symfony

volumes:
    db_app:

networks:
    symfony:
